### ISSUE TITLE
Screencapturing der Demo

### ISSUE THREAD

**Issue by MarkusTiede** [open-prevo/slides#7]
Die Idee war OBS Studio zu verwenden. Aber auf dem Notebook von @hoehnb bleibt der Inhalt aktuell noch schwarz.

**Comment by jochenpilger** [comment]
@hoehnb hat ein Video mit unserem Schwesterprojekt https://github.com/obsproject/obs-studio erstellt ;-)

**Comment by jochenpilger** [comment]
**Whats about?**
OpenGL-based 3D visualisation tool for source control repositories.
https://github.com/acaudwell/Gource

**Needed**

- Git
- Gource
- ffmpeg
- Durchblick bei den Parametern

**typische Befehle**
```
gource --logo openprevo.png -f -1280x720 --key --disable-progress --seconds-per-day 0.5 --auto-skip-seconds 0.1 --title "History of OpenPrevo - Gource - development visualization (june 2018 - july 2018)" --stop-at-end --file-idle-time 0 --hide filenames,progress,mouse --output-ppm-stream openprevo.out

C:\Users\User\Downloads\ffmpeg-20180726-bce4da8-win64-static\bin\ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i openprevo.out -vcodec libx264 -fpre "C:\Users\User\Downloads\ffmpeg-20180726-bce4da8-win64-static\presets\libvpx-720p.ffpreset" openprevo_gource.x264.avi
```

Upload auf Youtube:
https://www.youtube.com/watch?v=rUL5tlhvwM0
